### ISSUE TITLE
Throwingan unhandled exception with logstash 1.5.2

### ISSUE THREAD

**Issue by debraj-manna** [logstash-plugins/logstash-output-datadog#4]
I am trying to submit some events to datadog from logstash. Below is my logstash config:-

```
input {
 stdin{ 
 type => "stdin-type" 
 codec => json {}
 }
}

output { 
  if "_jsonparsefailure" in [tags] {
    stdout { codec => rubydebug }
    datadog {
      api_key => "xxxxxx"      
    }
  }  
}
```

On typing some non-json input (let's say `hello`) in STDIN of logstash I am getting the below output and not seeing any events in datadog.

```
Logstash startup completed
hello
{
       "message" => "hello",
          "tags" => [
        [0] "_jsonparsefailure"
    ],
      "@version" => "1",
    "@timestamp" => "2015-09-05T16:55:41.652Z",
          "type" => "stdin-type",
          "host" => "jabong-1383"
}
Unhandled exception {:request=>"#<Net::HTTP::Post POST>", :response=>"#<Net::HTTPAccepted 202 Accepted readbody=true>", :exception=>"RuntimeError", :level=>:warn}
```

Logstash Version 1.5.2

**Comment by guyboertje** [comment]
@debraj-manna - I am not sure why you are not seeing an event in Datadog, because the 'Unhandled exception' indicates that the correct response was returned `202 Accepted`.

The code is incorrectly expecting a `200 OK` response and raising the exception you are seeing.

Either the plugin code was always wrong or Datadog have changed the v1 event post API response code.

**Comment by jsvd** [comment]
just for reference, we can see the api can return 202 on event posts https://docs.datadoghq.com/api/?lang=ruby#post-an-event
